# print("Welcom to exceptions concept")
# print("Now it is fine")

# fo.open("nari.txt")



my_list=[3,4,5]


try:
    print(my_list[4])

except Exception as e:
    print("This is because of ",e)

    
